# Generated by Django 5.0.3 on 2024-03-11 14:48

import centuryproperties.apps.realestates.sql
import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=50)),
                ('company_logo', models.ImageField(blank=True, default='company_logo/default_company_logo/default_company_logo.jpeg', null=True, upload_to='company_logo/')),
                ('company_phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('short_bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='short_bio')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='bio')),
                ('address', models.CharField(blank=True, default='', max_length=128, verbose_name='address')),
                ('zip', models.CharField(blank=True, default='', max_length=20, verbose_name='zip')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='country')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default_profile_pic/default.jpg', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_employeepaymenrecord', to='realestates.employees')),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber1', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('phoneNumber2', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_employee', to='realestates.employees')),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_payments', to='realestates.employees')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payment', to='realestates.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to='realestates.employees')),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_total_amount', to='realestates.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employess_total_amount', to='realestates.employees')),
            ],
        ),
    ]
