# Generated by Django 5.0.3 on 2024-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
