# Generated by Django 5.0.3 on 2024-04-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0002_payment_installment_date_payment_installment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_employee', to='realestates.employees'),
        ),
    ]
