# Generated by Django 5.0.3 on 2024-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0003_alter_client_phonenumber1_alter_client_phonenumber2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
