# Generated by Django 5.0.3 on 2024-04-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0003_alter_client_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payments', to='realestates.employees'),
        ),
    ]
