# Generated by Django 5.0.3 on 2024-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0004_alter_payment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plot_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='plot_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
