# Generated by Django 5.0.3 on 2024-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0005_client_plot_number_payment_plot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
