# Generated by Django 5.0.3 on 2024-03-07 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0006_alter_client_phonenumber1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber1',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
