# Generated by Django 5.0.3 on 2024-06-15 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestates", "0006_alter_client_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phoneNumber1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phoneNumber2",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
    ]
