# Generated by Django 5.0.3 on 2024-03-07 20:02

import centuryproperties.apps.realestates.sql
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0007_alter_client_phonenumber1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_employeepaymenrecord', to='realestates.employees')),
            ],
            bases=(centuryproperties.apps.realestates.sql.TruncateTableMixin, models.Model),
        ),
    ]
