# Generated by Django 5.0.3 on 2024-06-23 17:30

import centuryproperties.apps.realestates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0008_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            bases=(centuryproperties.apps.realestates.models.TruncateTableMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='client',
            name='plot_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plot_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='realestates.employees'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='realestates.client'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='realestates.employees'),
        ),
        migrations.CreateModel(
            name='ClientLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('total_installments', models.PositiveIntegerField(default=0)),
                ('total_amount_paid', models.IntegerField(default=0)),
                ('remaining_amount', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_lands', to='realestates.client')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_lands', to='realestates.land')),
            ],
            bases=(centuryproperties.apps.realestates.models.TruncateTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='realestates.clientland'),
        ),
    ]
