# Generated by Django 5.0.3 on 2024-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0008_employeepaymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
