# Generated by Django 5.0.3 on 2024-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0009_clientland_land_delete_monthlytotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='exclude_from_reassignment',
            field=models.BooleanField(default=False),
        ),
    ]
