# Generated by Django 5.0.3 on 2024-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0009_land_remove_client_plot_number_remove_payment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
