# Generated by Django 5.0.3 on 2024-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0010_employees_exclude_from_reassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
