# Generated by Django 5.0.3 on 2024-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0010_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientland',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
