# Generated by Django 5.0.3 on 2024-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0010_alter_employees_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_pic/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
