# Generated by Django 5.0.3 on 2024-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0011_alter_employees_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_logo/default_company_logo/default_company_logo.jpeg', null=True, upload_to='company_logo/'),
        ),
    ]
