# Generated by Django 5.0.3 on 2024-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0011_clientland_payment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='commission',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
