# Generated by Django 5.0.3 on 2024-07-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0011_client_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='client_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='realestates.clientland'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('phoneNumber1',), name='unique_phoneNumber1'),
        ),
    ]
