# Generated by Django 5.0.3 on 2024-07-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0012_commission_client_land_client_unique_phonenumber1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('employee', 'client', 'client_land')},
        ),
    ]
