# Generated by Django 5.0.3 on 2024-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0012_remove_commission_last_updated_commission_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientland',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
