# Generated by Django 5.0.3 on 2024-07-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0013_alter_commission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepaymentrecord',
            name='client_land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='realestates.clientland'),
        ),
    ]
