# Generated by Django 5.0.3 on 2024-06-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0014_alter_monthlytotal_month_alter_totalamount_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyTotal',
        ),
        migrations.DeleteModel(
            name='TotalAmount',
        ),
    ]
