# Generated by Django 5.0.3 on 2024-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0014_employeepaymentrecord_client_land'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='is_confirmed',
            new_name='is_show',
        ),
        migrations.AddConstraint(
            model_name='land',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='price_gt_0'),
        ),
    ]
