# Generated by Django 5.0.3 on 2024-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0015_rename_is_confirmed_employees_is_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
