# Generated by Django 5.0.3 on 2024-06-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0015_delete_monthlytotal_delete_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepaymentrecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_payment_records', to='realestates.employees'),
        ),
    ]
