# Generated by Django 5.0.3 on 2024-06-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0016_alter_employeepaymentrecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepaymentrecord',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeepaymentrecord',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepaymentrecord',
            name='total_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeepaymentrecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='realestates.employees'),
        ),
    ]
