# Generated by Django 5.0.3 on 2024-06-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0017_employeepaymentrecord_installment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepaymentrecord',
            name='installment_number',
        ),
        migrations.RemoveField(
            model_name='employeepaymentrecord',
            name='total_installments',
        ),
    ]
