# Generated by Django 5.0.3 on 2024-06-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0018_remove_employeepaymentrecord_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepaymentrecord',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='realestates.client'),
        ),
    ]
